name: Publish to PyPI on Version Bump

on:
  push:
    branches:
      - master
    paths:
      - 'pyproject.toml'  # Only run if pyproject.toml changes

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for Trusted Publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # For tomllib

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install dependencies
        run: uv pip install packaging requests --system  # Add requests for PyPI API

      - name: Extract version from pyproject.toml
        id: get-version
        run: |
          VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Check latest version on PyPI
        id: check-pypi
        run: |
          PACKAGE_NAME=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['name'])")
          LATEST_PYPY_VERSION=$(python -c "import requests; print(requests.get(f'https://pypi.org/pypi/$PACKAGE_NAME/json').json()['info']['version'])")
          echo "LATEST_PYPY_VERSION=$LATEST_PYPY_VERSION" >> $GITHUB_OUTPUT

      - name: Compare versions and publish
        run: |
          CURRENT_VERSION="${{ steps.get-version.outputs.VERSION }}"
          LATEST_PYPY_VERSION="${{ steps.check-pypi.outputs.LATEST_PYPY_VERSION }}"

          # Compare versions using Python
          python -c "from packaging import version; exit(0 if version.parse('$CURRENT_VERSION') > version.parse('$LATEST_PYPY_VERSION') else 1)" || {
            echo "Current version ($CURRENT_VERSION) is not greater than PyPI version ($LATEST_PYPY_VERSION), skipping publish"
            exit 0
          }

          echo "New version detected: $CURRENT_VERSION > $LATEST_PYPY_VERSION, publishing..."
          uv build
          uv publish